openapi: 3.0.1
info:
  contact:
    email: getinfo@czertainly.com
    name: CZERTAINLY
    url: https://www.czertainly.com
  description: REST API for implementations of custom Discovery Provider
  license:
    name: MIT License
    url: https://github.com/3KeyCompany/CZERTAINLY/blob/develop/LICENSE.md
  title: CZERTAINLY Discovery Provider API
  version: 2.11.0
  x-logo:
    url: images/czertainly_color_H.svg
externalDocs:
  description: CZERTAINLY Documentation
  url: https://docs.czertainly.com
servers:
- url: /
tags:
- description: "Discovery Provider API. Used to schedule and establish certificate\
    \ discovery process. Once the discovery process is started, the progress and the\
    \ history of the certificate discovery can be requested. Discovery provides information\
    \ about discovered certificates and meta data that are specific to implementation\
    \ of the discovery provider."
  name: Discovery
- description: "Connector Information API. Each connector may have multiple functions\
    \ represented by FunctionGroupCode. For each FunctionGroupCode there is a list\
    \ of implemented end points. These endpoints must be according the specified interface,\
    \ this is validated by the core. You can also implement helper end points that\
    \ are used for callbacks and other relevant operations specific to implementation."
  name: Connector Info
- description: "Connector Health check API. Connector returns own status and in some\
    \ cases can return status of services on which it depends like database, HSM and\
    \ so on."
  name: Health check
- description: Connector Attributes API. Provides information about supported Attributes
    of the connector. Attributes are specific to implementation and gives information
    about the data that can be exchanged and properly parsed by the connector. Part
    of this API is validation of the Attributes.
  name: Connector Attributes
- description: Certificate Management API
  name: Certificate Management
- description: Authority Management API
  name: Authority Management
paths:
  /v1/discoveryProvider/discover/{uuid}:
    delete:
      operationId: deleteDiscovery
      parameters:
      - description: Discovery UUID
        explode: false
        in: path
        name: uuid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Discovery information deleted
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete Discovery
      tags:
      - Discovery
    post:
      operationId: getDiscovery
      parameters:
      - description: Discovery UUID
        explode: false
        in: path
        name: uuid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
        "200":
          description: Discovery details retrieved
        "400":
          description: Bad Request
      summary: Get Discovery status and result
      tags:
      - Discovery
  /v2/authorityProvider/authorities/{uuid}/certificates/issue/attributes/validate:
    post:
      operationId: validateIssueCertificateAttributes
      parameters:
      - description: Authority Instance UUID
        explode: false
        in: path
        name: uuid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
        "200":
          description: Attributes validated
        "400":
          description: Bad Request
        "404":
          description: Not Found
      summary: Validate list of Attributes to issue Certificate
      tags:
      - Certificate Management
  /v2/authorityProvider/authorities/{uuid}/certificates/revoke:
    post:
      operationId: revokeCertificate
      parameters:
      - description: Authority Instance UUID
        explode: false
        in: path
        name: uuid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
        "200":
          description: Certificate revoked
        "400":
          description: Bad Request
      summary: Revoke Certificate
      tags:
      - Certificate Management
  /v2/authorityProvider/authorities/{uuid}/certificates/revoke/attributes:
    get:
      operationId: listRevokeCertificateAttributes
      parameters:
      - description: Authority Instance UUID
        explode: false
        in: path
        name: uuid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
        "200":
          description: Revoke certificate attribute list retrieved
        "400":
          description: Bad Request
        "404":
          description: Not Found
      summary: List of Attributes to revoke Certificate
      tags:
      - Certificate Management
  /v1:
    get:
      description: Returns map of functional code and implemented end points
      operationId: listSupportedFunctions
      responses:
        "200":
          description: Functions found
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: List supported functions of the connector
      tags:
      - Connector Info
  /v1/authorityProvider/authorities/{uuid}:
    delete:
      operationId: removeAuthorityInstance
      parameters:
      - description: Authority Instance UUID
        explode: false
        in: path
        name: uuid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Authority instance removed
        "204":
          description: No Content
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Remove Authority instance
      tags:
      - Authority Management
    get:
      operationId: getAuthorityInstance
      parameters:
      - description: Authority Instance UUID
        explode: false
        in: path
        name: uuid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Authority instance retrieved
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get an Authority instance
      tags:
      - Authority Management
    post:
      operationId: updateAuthorityInstance
      parameters:
      - description: Authority Instance UUID
        explode: false
        in: path
        name: uuid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Authority instance updated
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Update Authority instance
      tags:
      - Authority Management
  /v1/authorityProvider/authorities/{uuid}/connect:
    get:
      operationId: getConnection
      parameters:
      - description: Authority Instance UUID
        explode: false
        in: path
        name: uuid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Authority instance connected
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Connect to Authority
      tags:
      - Authority Management
  /v1/authorityProvider/authorities/{uuid}/raProfile/attributes:
    get:
      operationId: listRAProfileAttributes
      parameters:
      - description: Authority Instance UUID
        explode: false
        in: path
        name: uuid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: RA Profile Attributes retrieved
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: List RA Profile Attributes
      tags:
      - Authority Management
  /v1/authorityProvider/authorities/{uuid}/caCertificates:
    post:
      description: "Returns the Authority Instance's certificate chain. The chain\
        \ is returned as a list of Base64 encoded certificates, starting with the\
        \ Authority Instance's certificate and ending with the root certificate, if\
        \ available."
      operationId: getCaCertificates
      parameters:
      - description: Authority Instance UUID
        explode: false
        in: path
        name: uuid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Authority Instance's certificate chain retrieved
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get the Authority Instance's certificate chain
      tags:
      - Authority Management
  /v1/authorityProvider/{kind}/attributes/validate:
    post:
      operationId: validateAttributesMixin0
      parameters:
      - description: Kind
        explode: false
        in: path
        name: kind
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Attribute validation completed
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "422":
          description: Attribute validation failed
        "500":
          description: Internal Server Error
      summary: Validate Attributes
      tags:
      - Connector Attributes
  /v2/authorityProvider/authorities/{uuid}/certificates/identify:
    post:
      operationId: identifyCertificate
      parameters:
      - description: Authority Instance UUID
        explode: false
        in: path
        name: uuid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Certificate identified
        "400":
          description: Bad Request
        "404":
          description: Certificate unknown
        "422":
          description: Unprocessable Entity. Certificate is found but not valid according
            to supplied RA attributes
        "500":
          description: Internal Server Error
      summary: Identify Certificate
      tags:
      - Certificate Management
  /v2/authorityProvider/authorities/{uuid}/certificates/issue/attributes:
    get:
      operationId: listIssueCertificateAttributes
      parameters:
      - description: Authority Instance UUID
        explode: false
        in: path
        name: uuid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
        "200":
          description: Issue certificate attribute list retrieved
      summary: List of Attributes to issue Certificate
      tags:
      - Certificate Management
  /v1/discoveryProvider/{kind}/attributes:
    get:
      operationId: listAttributeDefinitions
      parameters:
      - description: Kind
        explode: false
        in: path
        name: kind
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Attributes retrieved
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: List available Attributes
      tags:
      - Connector Attributes
  /v1/discoveryProvider/{kind}/attributes/validate:
    post:
      operationId: validateAttributes
      parameters:
      - description: Kind
        explode: false
        in: path
        name: kind
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Attribute validation completed
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "422":
          description: Attribute validation failed
        "500":
          description: Internal Server Error
      summary: Validate Attributes
      tags:
      - Connector Attributes
  /v2/authorityProvider/authorities/{uuid}/certificates/issue:
    post:
      operationId: issueCertificate
      parameters:
      - description: Authority Instance UUID
        explode: false
        in: path
        name: uuid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
        "200":
          description: Certificate issued
        "400":
          description: Bad Request
        "404":
          description: Not Found
      summary: Issue Certificate
      tags:
      - Certificate Management
  /v2/authorityProvider/authorities/{uuid}/certificates/revoke/attributes/validate:
    post:
      operationId: validateRevokeCertificateAttributes
      parameters:
      - description: Authority Instance UUID
        explode: false
        in: path
        name: uuid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
        "200":
          description: Attributes validated
        "400":
          description: Bad Request
      summary: Validate list of Attributes to revoke certificate
      tags:
      - Certificate Management
  /v1/discoveryProvider/discover:
    post:
      operationId: discoverCertificate
      responses:
        "500":
          description: Internal Server Error
        "200":
          description: Discovery initiated
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "422":
          description: Unprocessable entity
      summary: Initiate certificate Discovery
      tags:
      - Discovery
  /v1/health:
    get:
      operationId: checkHealth
      responses:
        "200":
          description: Health check completed successfully
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Health check
      tags:
      - Health check
  /v2/authorityProvider/authorities/{uuid}/certificates/renew:
    post:
      operationId: renewCertificate
      parameters:
      - description: Authority Instance UUID
        explode: false
        in: path
        name: uuid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "500":
          description: Internal Server Error
        "200":
          description: Certificate renewed
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
      summary: Renew Certificate
      tags:
      - Certificate Management
  /v1/authorityProvider/authorities:
    get:
      operationId: listAuthorityInstances
      responses:
        "200":
          description: Authority instance list retrieved
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: List Authority instances
      tags:
      - Authority Management
    post:
      operationId: createAuthorityInstance
      responses:
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
        "200":
          description: Authority instance created
      summary: Create Authority instance
      tags:
      - Authority Management
  /v1/authorityProvider/authorities/{uuid}/crl:
    post:
      description: "Returns the latest CRL for the Authority Instance. If delta is\
        \ true, the delta CRL is returned, otherwise the full CRL is returned. When\
        \ the CRL is not available for Authority Instance, null data is returned."
      operationId: getCrl
      parameters:
      - description: Authority Instance UUID
        explode: false
        in: path
        name: uuid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: CRL retrieved
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get the latest CRL for the Authority Instance
      tags:
      - Authority Management
  /v1/authorityProvider/authorities/{uuid}/raProfile/attributes/validate:
    post:
      operationId: validateRAProfileAttributes
      parameters:
      - description: Authority Instance UUID
        explode: false
        in: path
        name: uuid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
        "200":
          description: RA Profile Attributes information validated
      summary: Validate RA Profile attributes
      tags:
      - Authority Management
  /v1/authorityProvider/{kind}/attributes:
    get:
      operationId: listAttributeDefinitionsMixin0
      parameters:
      - description: Kind
        explode: false
        in: path
        name: kind
        required: true
        schema:
          type: string
        style: simple
      responses:
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
        "200":
          description: Attributes retrieved
        "400":
          description: Bad Request
      summary: List available Attributes
      tags:
      - Connector Attributes
components:
  schemas: {}
